### PR TITLE
Update runtime to 47

### LINKED ISSUE #13: runtime org.gnome.Platform branch 45 is end-of-life
```
Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   org.gnome.EasyTAG
```

### PR DESCRIPTION
**Pull request by X-m7**
Fixes #13

### CODE REVIEW

**Comment by X-m7** [comment]
bot, build

**Comment by ghost** [comment]
@bbhtt I tihnk it's ready for review.

**Comment by X-m7** [comment]
Oh silly me, I forgot to press the merge button, thanks for the reminder!

**Comment by ghost** [comment]
The EOL warning is still present. 

```
Uses an end-of-life runtime
The runtime used by this app is no longer receiving security updates
```

Source: https://flathub.org/apps/org.gnome.EasyTAG

almost 8 years ago (Built 9 months ago)

**Comment by X-m7** [comment]
Huh, so the test build works but not when pushed to master...

Except on master the x86_64 build works but not the aarch64 one...

Because of a wrong checksum even though both the aarch64 and x86_64 builds should use the same files anyway??? https://buildbot.flathub.org/#/builders/31/builds/14868

Edit: Just tried to start the build manually, hopefully I did things right: https://buildbot.flathub.org/#/buildrequests/650607

**Pull request merged**
